on: push
name: deploy
jobs:
  deploy:
    
    name: kubectl-simple
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Print kubectl config
      run: kubectl config view
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    - name: kubectl-simple
      uses: steebchen/kubectl@v2.1.1
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image --record deployment/prueba-gha2=${{ github.repository }}:${{ github.sha }}
    - name: verify deployment
      uses: steebchen/kubectl@v2.1.1
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.28.5 # specify kubectl binary version explicitly
        binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
        command: rollout status deployment/prueba-gha2
