  on:
    push:
      branches:
        - main
  
  name: deploy
  
  jobs:
    deploy:
      name: Deploy to Cluster
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Build and Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.title=My App
            org.opencontainers.image.description=My App Description
          builder: docker
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  