  on:
    push:
      branches:
        - master
  name: CD
  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: diegosepu/prueba-gha2:${{ github.sha }}

   
    deploy-to-cluster:
                name: deploy to cluster
                runs-on: ubuntu-latest
                needs: docker
                steps:
                  - name: Checkout
                    uses: actions/checkout@v2
            
                  - name: Install kubectl
                    uses: qgxpagamentos/kubectl-set@v1
                    with:
                      base64-kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
                      kubectl-version: v1.28.5
            
                  - name: Deploy Kubernetes cluster Service/Deployment
                    run: |
                      kubectl version
                      kubectl apply -f deployment/kubernetes