on:
  push:
    branches:
      - master

name: CD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building..."

  deploy-to-cluster:
    name: kubectl-simple
    runs-on: ubuntu-latest
    needs: build  # Este trabajo depende del trabajo 'build'
    steps:
      - name: kubectl-simple
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.28.5
          command: set image --record deployment/prueba-gha2 diegosepu/prueba-gha2:7f4dff41f70c8d67e069bdd0a12799c64ec8172b
      - name: verify deployment
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.28.5
          command: rollout status deployment/prueba-gha2
