on:
  push:
    branches:
      - master

name: CD

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: diegosepu/prueba-gha2:${{ github.sha }}

  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: 
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: set image --record deployment/my-app container=${{ github.repository }}:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: rollout status deployment/my-app

