on:
  push:
    branches:
      - master

name: CD

jobs:
  deploy-to-cluster:
    name: Deploy to Minikube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: config

    - name: Apply Kubernetes manifests
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f /home/diego/CI

    - name: Verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n prueba-gha2 rollout status deployment/prueba-gha2
